# generated by datamodel-codegen:
#   filename:  application_env_config.openapi.json
#   timestamp: 2025-05-21T18:55:55+00:00

from __future__ import annotations
from enum import Enum
from typing import Any, Dict, List, Optional, Union
from pydantic import BaseModel, ConfigDict, Field, RootModel, conint


class EndpointType(Enum):
    REQ = "REQ"


class EndpointConfigReq(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    endpoint_key: str
    endpoint_name: str
    endpoint_type: EndpointType
    interface_name: Optional[str] = None
    provider_message_type: str
    requester_message_type: str


class EndpointType1(Enum):
    PRV = "PRV"


class EndpointConfigPrv(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    endpoint_key: str
    endpoint_name: str
    endpoint_type: EndpointType1
    interface_name: Optional[str] = None
    provider_message_type: str
    requester_message_type: str


class EndpointConfig(RootModel[Union[EndpointConfigReq, EndpointConfigPrv]]):
    root: Union[EndpointConfigReq, EndpointConfigPrv]


class GpioLineInfo(BaseModel):
    active_state: str
    consumer: Optional[str] = None
    direction: str
    line_offset: conint(ge=0)
    name: Optional[str] = None
    used: bool


class I2cDetectedDevice(BaseModel):
    address: str
    description: Optional[str] = None


class MappedURL(BaseModel):
    public_ip: Optional[str] = None
    public_port: Optional[conint(ge=0)] = None
    vpn_ip: str
    vpn_port: conint(ge=0)


class PeripheralType1(Enum):
    Camera = "Camera"


class PeripheralType2(Enum):
    RealSense = "RealSense"


class PeripheralType3(Enum):
    Speaker = "Speaker"


class PeripheralType4(Enum):
    Keyboard = "Keyboard"


class PeripheralType5(Enum):
    Mouse = "Mouse"


class PeripheralType6(Enum):
    Microphone = "Microphone"


class PeripheralType7(Enum):
    GPU = "GPU"


class PeripheralType8(Enum):
    I2C = "I2C"


class PeripheralType9(Enum):
    GPIO = "GPIO"


class PeripheralType10(Enum):
    ISP = "ISP"


class PeripheralType11(Enum):
    Codec = "Codec"


class PeripheralType12(Enum):
    Rendering = "Rendering"


class PeripheralType13(Enum):
    GenericDevice = "GenericDevice"


class PeripheralTypeOther(BaseModel):
    Other: str


class PeripheralType(
    RootModel[
        Union[
            PeripheralType1,
            PeripheralType2,
            PeripheralType3,
            PeripheralType4,
            PeripheralType5,
            PeripheralType6,
            PeripheralType7,
            PeripheralType8,
            PeripheralType9,
            PeripheralType10,
            PeripheralType11,
            PeripheralType12,
            PeripheralType13,
            PeripheralTypeOther,
        ]
    ]
):
    root: Union[
        PeripheralType1,
        PeripheralType2,
        PeripheralType3,
        PeripheralType4,
        PeripheralType5,
        PeripheralType6,
        PeripheralType7,
        PeripheralType8,
        PeripheralType9,
        PeripheralType10,
        PeripheralType11,
        PeripheralType12,
        PeripheralType13,
        PeripheralTypeOther,
    ]


class ProtocolEnum(Enum):
    TCP = "TCP"
    UDP = "UDP"
    SCTP = "SCTP"
    HTTP = "HTTP"
    WS = "WS"
    SSH = "SSH"


class PublishMode(Enum):
    Ingress = "Ingress"
    Host = "Host"


class RealSenseCameraPeripheral(BaseModel):
    device_nodes: List[str]
    model: str
    name: str
    peripheral_type: PeripheralType
    serial_number: str


class RenderingPeripheral(BaseModel):
    device_nodes: List[str]
    max_performance: Optional[conint(ge=0)] = None
    name: str
    peripheral_type: PeripheralType
    supported_apis: List[str]


class Client(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    interface_name: Optional[str] = None
    key: str
    name: str
    spec: str


class ServiceConfigClient(BaseModel):
    Client_1: Client = Field(..., alias="Client", description="The service is a client")


class Server(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    interface_name: Optional[str] = None
    key: str
    name: str
    spec: str


class ServiceConfigServer(BaseModel):
    Server_1: Server = Field(..., alias="Server", description="The service is a server")


class ServiceConfig(RootModel[Union[ServiceConfigClient, ServiceConfigServer]]):
    root: Union[ServiceConfigClient, ServiceConfigServer]


class TopicType(Enum):
    PUB = "PUB"


class TopicConfigPub(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    interface_name: Optional[str] = None
    message_type: str
    topic_key: str
    topic_name: str
    topic_type: TopicType


class TopicType1(Enum):
    SUB = "SUB"


class TopicConfigSub(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    interface_name: Optional[str] = None
    message_type: str
    topic_key: str
    topic_name: str
    topic_type: TopicType1


class TopicConfig(RootModel[Union[TopicConfigPub, TopicConfigSub]]):
    root: Union[TopicConfigPub, TopicConfigSub]


class URLMapping(BaseModel):
    name_to_url: Dict[str, MappedURL]


class CameraPeripheral(BaseModel):
    camera_type: Optional[str] = None
    device_nodes: List[str]
    name: str
    peripheral_type: PeripheralType
    protocol: Optional[str] = None
    reference: str
    volumes: List[List]


class CodecPeripheral(BaseModel):
    device_nodes: List[str]
    name: str
    peripheral_type: PeripheralType
    supported_codecs: List[str]


class GenericDevicePeripheral(BaseModel):
    device_node: str
    name: str
    peripheral_type: PeripheralType


class GpioPeripheral(BaseModel):
    chip_name: str
    device_nodes: List[str]
    label: str
    lines: List[GpioLineInfo]
    num_lines: conint(ge=0)
    peripheral_type: PeripheralType


class GpuPeripheral(BaseModel):
    device_nodes: List[str]
    index: Optional[conint(ge=0)] = None
    model: str
    name: str
    peripheral_type: PeripheralType
    vram: Optional[conint(ge=0)] = None


class I2cPeripheral(BaseModel):
    bus_number: conint(ge=0)
    detected_devices: List[I2cDetectedDevice]
    device_nodes: List[str]
    name: str
    peripheral_type: PeripheralType


class IspPeripheral(BaseModel):
    device_nodes: List[str]
    name: str
    peripheral_type: PeripheralType
    supported_features: List[str]


class OtherPeripheral(BaseModel):
    device_nodes: List[str]
    name: str
    peripheral_type: PeripheralType
    reference: str


class PeripheralGpu(BaseModel):
    GPU: GpuPeripheral


class PeripheralI2C(BaseModel):
    I2C: I2cPeripheral


class PeripheralGpio(BaseModel):
    GPIO: GpioPeripheral


class PeripheralCamera(BaseModel):
    Camera: CameraPeripheral


class PeripheralRealSense(BaseModel):
    RealSense: RealSenseCameraPeripheral


class PeripheralIsp(BaseModel):
    ISP: IspPeripheral


class PeripheralCodec(BaseModel):
    Codec: CodecPeripheral


class PeripheralRendering(BaseModel):
    Rendering: RenderingPeripheral


class PeripheralSpeaker(BaseModel):
    Speaker: OtherPeripheral


class PeripheralKeyboard(BaseModel):
    Keyboard: OtherPeripheral


class PeripheralMouse(BaseModel):
    Mouse: OtherPeripheral


class PeripheralGenericDevice(BaseModel):
    GenericDevice: GenericDevicePeripheral


class PeripheralOther(BaseModel):
    Other: OtherPeripheral


class Peripheral(
    RootModel[
        Union[
            PeripheralGpu,
            PeripheralI2C,
            PeripheralGpio,
            PeripheralCamera,
            PeripheralRealSense,
            PeripheralIsp,
            PeripheralCodec,
            PeripheralRendering,
            PeripheralSpeaker,
            PeripheralKeyboard,
            PeripheralMouse,
            PeripheralGenericDevice,
            PeripheralOther,
        ]
    ]
):
    root: Union[
        PeripheralGpu,
        PeripheralI2C,
        PeripheralGpio,
        PeripheralCamera,
        PeripheralRealSense,
        PeripheralIsp,
        PeripheralCodec,
        PeripheralRendering,
        PeripheralSpeaker,
        PeripheralKeyboard,
        PeripheralMouse,
        PeripheralGenericDevice,
        PeripheralOther,
    ]


class PortConfig(BaseModel):
    is_system_interface: Optional[bool] = None
    name: str
    protocol: Optional[ProtocolEnum] = None
    publish_mode: Optional[PublishMode] = None
    published_port: conint(ge=0) = Field(..., description="The port on the swarm hosts.")
    target_port: conint(ge=0) = Field(..., description="The port inside the container.")


class MountedPeripheral(BaseModel):
    name: str = Field(
        ...,
        description="The name of the peripheral. That is used by the application version to identify the peripheral",
    )
    peripheral: Peripheral


class MountedPeripherals(BaseModel):
    peripherals: List[MountedPeripheral]


class ApplicationEnvConfig(BaseModel):
    application_id: str
    application_name: str
    config: Any
    deployed_application_id: str
    deployed_application_name: str
    endpoints: List[EndpointConfig]
    entrypoint_name: Optional[str] = None
    git_branch: Optional[str] = None
    git_url: Optional[str] = None
    is_release_version: bool
    peripherals: MountedPeripherals
    port_config: List[PortConfig]
    public_ip: Optional[str] = None
    services: List[ServiceConfig]
    storage_access_key: Optional[str] = None
    storage_endpoint_url: Optional[str] = None
    storage_secret_key: Optional[str] = None
    storage_url: Optional[str] = None
    system_id: str
    topics: List[TopicConfig]
    url_mapping: URLMapping
    vpn_ip: str
