site_name: make87 Python3 SDK

theme:
  name: material
  palette:
    scheme: slate
    primary: orange
    accent: deep orange
  favicon: https://make87.com/favicon.ico
  logo: https://make87-files.nyc3.digitaloceanspaces.com/assets/branding/icon/make87_ME_1d_Icon_cv.svg

nav:
  - Home: index.md
  - API Reference: reference/

plugins:
  - search
  - autorefs
  - gen-files:
      scripts:
        - docs/scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
