site_name: Python3 SDK | make87
docs_dir: src
nav:
  - Home: index.md
  - API Reference: reference/
plugins:
  - search:
      lang:
        - en
      separator: '[\s\-\.]+'
      pipeline: # Improves keyword matching
        - stemmer
        - stopWordFilter
        - trimmer
  - macros:
      on_undefined: strict
  - glightbox
  - autorefs
  - gen-files:
      scripts:
        - src/scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.superfences # used for tabbed code blocks
  - pymdownx.tabbed: # used for tabbed code blocks
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
theme:
  name: material
  favicon: assets/images/favicon-32x32.png # Path to your custom favicon
  logo: assets/images/make87_ME_1d_Icon_cv.svg # Path to your custom logo
  font:
    code: JetBrains Mono
  icon:
    admonition:
      roadmap: material/map
  features:
    - navigation.tracking # Optional, improves UX
    - navigation.indexes # Ensures section index pages work well
    - navigation.tabs # Enables tab-based navigation
    - content.action # Enables click-to-expand on images
    - content.code.copy
    - content.tabs.link
  palette:
    - scheme: slate
      primary: amber
      accent: amber
#extra_css:
#  - assets/extra.css
extra:
  generator: false # Removes "Made with MkDocs" footer
  variables:
    product: make87
    node_client: node client
    website: https://www.make87.com
    web_app: https://app.make87.com
  version: 0.0.1 # Version of the documentation - will be auto-updated by CI
validation:
  links:
    absolute_links: relative_to_docs
    anchors: warn
    unrecognized_links: warn
